nguage: ruby
rvm:
- 2.0.0
before_script:
- psql -c "create role enpit with password 'enpit' login createdb;" -U postgres
script:
- bundle exec rake db:drop db:create db:migrate
- bundle exec rake
deploy:
  provider: heroku
  api_key:
    secure: OcFz5jgaZ5ljRIYP8cBde4H43niJK50s1hUrz8j+mNJfJUSHlayVqCSF5Xo5NHp/3ucnDJ+kHkB7Yz7RQgZ3upbu6JvDZpAPKXkudxRv+9sCIuHWBjiCONjqJCud1h7upQtjWbwdd3eyxiG3U1prfwlMtgcorkdQ/uJuSKjQOYc=
  app: denka
  on:
    repo: NoguHiro/hacky_and_rocky
