nguage: ruby
rvm:
  - "2.0.0"
before_script:
  - psql -c "create role enpit with password 'enpit' login createdb;" -U postgres
script:
  - "bundle exec rake db:drop db:create db:migrate"
  - "bundle exec rake"
deploy:
  provider: heroku
  api_key: f5d0eb37-ba13-422d-9b88-18423390482c
  app: hackyandlocky
