nguage: ruby
rvm:
- 2.0.0
before_script:
- psql -c "create role enpit with password 'enpit' login createdb;" -U postgres
script:
- bundle exec rake db:drop db:create db:migrate
- bundle exec rake
deploy:
  provider: heroku
  api_key:
    secure: fDQZSYLS3Dfdm+P64UzPgk9Q+RJhSm4Jf18nfGSHSi2EwwfEjDQRHIU4OVDSabYs6XTKcL6CaO5A5rqWILY4nXrm4Wu535x9RlMlvFKpkABXdlQSbiQ5rqs0daQaLWtDeGGHddib1nP27qCLT38RJI7TwRds22QqdtQ4tWVR+IA=
  app: denka
  on:
    repo: NoguHiro/hacky_and_rocky
